// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addMember.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO room_members (room_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, character_id, role, joined_at
`

type AddMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.RoomID, arg.UserID, arg.Role)
	var i RoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
