// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characterLimit.sql

package db

import (
	"context"
)

const countUserCharacters = `-- name: CountUserCharacters :one
SELECT COUNT(*)
FROM characters
WHERE user_id = $1
`

func (q *Queries) CountUserCharacters(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCharacters, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lockUserForCharacterCreation = `-- name: LockUserForCharacterCreation :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserForCharacterCreation(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockUserForCharacterCreation, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
