// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanOldDiceRolls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanOldDiceRolls = `-- name: CleanOldDiceRolls :exec
DELETE FROM dice_rolls dr
WHERE dr.character_id = $1
  AND dr.id NOT IN (
      SELECT id FROM dice_rolls
      WHERE character_id = $1
      ORDER BY created_at DESC
      LIMIT 50
  )
`

func (q *Queries) CleanOldDiceRolls(ctx context.Context, characterID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cleanOldDiceRolls, characterID)
	return err
}
