// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanOldDiceRolls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanOldDiceRolls = `-- name: CleanOldDiceRolls :exec
DELETE FROM dice_rolls dr
USING characters c
WHERE c.id = dr.character_id
  AND c.user_id = $1
  AND dr.character_id = $2
  AND dr.id NOT IN (
      SELECT id FROM dice_rolls
      WHERE character_id = $2
      ORDER BY created_at DESC
      LIMIT 50
  )
`

type CleanOldDiceRollsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) CleanOldDiceRolls(ctx context.Context, arg CleanOldDiceRollsParams) error {
	_, err := q.db.Exec(ctx, cleanOldDiceRolls, arg.UserID, arg.CharacterID)
	return err
}
