// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createRoom.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (owner_id, name, max_players, invite_token, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, max_players, invite_token, created_at, updated_at, password_hash, last_activity_at, name
`

type CreateRoomParams struct {
	OwnerID      string `json:"owner_id"`
	Name         string `json:"name"`
	MaxPlayers   int32  `json:"max_players"`
	InviteToken  string `json:"invite_token"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.OwnerID,
		arg.Name,
		arg.MaxPlayers,
		arg.InviteToken,
		arg.PasswordHash,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.LastActivityAt,
		&i.Name,
	)
	return i, err
}
