// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createUser.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    clerk_user_id,
    username,
    email,
    avatar_url
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, clerk_user_id, username, email, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkUserID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
