// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacterSkill = `-- name: CreateCharacterSkill :one
WITH inserted AS (
    INSERT INTO skills (
        character_id,
        name,
        category_id,
        base_value,
        value,
        checked
    )
    SELECT
        c.id,
        $1,
        $2,
        $3,
        $4,
        $5
    FROM characters c
    WHERE c.user_id = $6
      AND c.id = $7
    RETURNING id, character_id, name, category_id, base_value, value, checked, created_at, updated_at, is_protected, base_rule
)
SELECT inserted.id, inserted.character_id, inserted.name, inserted.category_id, inserted.base_value, inserted.value, inserted.checked, inserted.created_at, inserted.updated_at, inserted.is_protected, inserted.base_rule,
    sc.name as category_name
FROM inserted
JOIN skills_categories sc ON inserted.category_id = sc.id
`

type CreateCharacterSkillParams struct {
	Name        string      `json:"name"`
	CategoryID  pgtype.UUID `json:"category_id"`
	BaseValue   int16       `json:"base_value"`
	Value       int16       `json:"value"`
	Checked     bool        `json:"checked"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

type CreateCharacterSkillRow struct {
	ID           pgtype.UUID        `json:"id"`
	CharacterID  pgtype.UUID        `json:"character_id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	BaseValue    int16              `json:"base_value"`
	Value        int16              `json:"value"`
	Checked      bool               `json:"checked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsProtected  bool               `json:"is_protected"`
	BaseRule     *string            `json:"base_rule"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) CreateCharacterSkill(ctx context.Context, arg CreateCharacterSkillParams) (CreateCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, createCharacterSkill,
		arg.Name,
		arg.CategoryID,
		arg.BaseValue,
		arg.Value,
		arg.Checked,
		arg.UserID,
		arg.CharacterID,
	)
	var i CreateCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.CategoryID,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
		&i.BaseRule,
		&i.CategoryName,
	)
	return i, err
}
