// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createNote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    character_id,
    title,
    body
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, character_id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.CharacterID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
