// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createBackstoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBackstoryItem = `-- name: CreateBackstoryItem :one
INSERT INTO backstory_items (
    backstory_id,
    section,
    title,
    text
)
SELECT
    b.id,
    $1,
    $2,
    $3
FROM backstories b
JOIN characters c ON c.id = b.character_id
WHERE c.user_id = $4
  AND b.character_id = $5
RETURNING id, backstory_id, section, title, text, created_at, updated_at
`

type CreateBackstoryItemParams struct {
	Section     string      `json:"section"`
	Title       string      `json:"title"`
	Text        string      `json:"text"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) CreateBackstoryItem(ctx context.Context, arg CreateBackstoryItemParams) (BackstoryItem, error) {
	row := q.db.QueryRow(ctx, createBackstoryItem,
		arg.Section,
		arg.Title,
		arg.Text,
		arg.UserID,
		arg.CharacterID,
	)
	var i BackstoryItem
	err := row.Scan(
		&i.ID,
		&i.BackstoryID,
		&i.Section,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
