// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createRoomDiceRoll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoomDiceRoll = `-- name: CreateRoomDiceRoll :one
INSERT INTO room_dice_rolls (room_id, dice_roll_id, user_id, kind, metadata)
SELECT $1, dr.id, dr.user_id, $2, $3
FROM dice_rolls dr
WHERE dr.id = $4
  AND dr.user_id = $5
  AND EXISTS (
      SELECT 1
      FROM room_members
      WHERE room_id = $1
        AND user_id = $5
  )
RETURNING id, room_id, dice_roll_id, user_id, kind, metadata, created_at
`

type CreateRoomDiceRollParams struct {
	RoomID     pgtype.UUID `json:"room_id"`
	Kind       string      `json:"kind"`
	Metadata   []byte      `json:"metadata"`
	DiceRollID pgtype.UUID `json:"dice_roll_id"`
	UserID     string      `json:"user_id"`
}

func (q *Queries) CreateRoomDiceRoll(ctx context.Context, arg CreateRoomDiceRollParams) (RoomDiceRoll, error) {
	row := q.db.QueryRow(ctx, createRoomDiceRoll,
		arg.RoomID,
		arg.Kind,
		arg.Metadata,
		arg.DiceRollID,
		arg.UserID,
	)
	var i RoomDiceRoll
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DiceRollID,
		&i.UserID,
		&i.Kind,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
