// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacterSkill = `-- name: CreateCharacterSkill :one
WITH inserted AS (
    INSERT INTO skills (
        character_id,
        name,
        category_id,
        base_value,
        value,
        checked,
        specialized,
        specialty_id
    )
    SELECT
        c.id,
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7::uuid
    FROM characters c
    WHERE c.user_id = $8
      AND c.id = $9
    RETURNING id, character_id, name, category_id, base_value, value, checked, specialized, specialty_id, created_at, updated_at
)
SELECT inserted.id, inserted.character_id, inserted.name, inserted.category_id, inserted.base_value, inserted.value, inserted.checked, inserted.specialized, inserted.specialty_id, inserted.created_at, inserted.updated_at,
    sc.name as category_name,
    ss.id as specialty_pk_id,
    ss.name as specialty_name,
    ss.description as specialty_description,
    ss.base_value as specialty_base_value,
    ss.created_at as specialty_created_at,
    ss.updated_at as specialty_updated_at
FROM inserted
JOIN skills_categories sc ON inserted.category_id = sc.id
LEFT JOIN skills_specialties ss ON inserted.specialty_id = ss.id
`

type CreateCharacterSkillParams struct {
	Name        string      `json:"name"`
	CategoryID  pgtype.UUID `json:"category_id"`
	BaseValue   int16       `json:"base_value"`
	Value       int16       `json:"value"`
	Checked     bool        `json:"checked"`
	Specialized bool        `json:"specialized"`
	SpecialtyID pgtype.UUID `json:"specialty_id"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

type CreateCharacterSkillRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CharacterID          pgtype.UUID        `json:"character_id"`
	Name                 string             `json:"name"`
	CategoryID           pgtype.UUID        `json:"category_id"`
	BaseValue            int16              `json:"base_value"`
	Value                int16              `json:"value"`
	Checked              bool               `json:"checked"`
	Specialized          bool               `json:"specialized"`
	SpecialtyID          pgtype.UUID        `json:"specialty_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CategoryName         string             `json:"category_name"`
	SpecialtyPkID        pgtype.UUID        `json:"specialty_pk_id"`
	SpecialtyName        *string            `json:"specialty_name"`
	SpecialtyDescription *string            `json:"specialty_description"`
	SpecialtyBaseValue   *int16             `json:"specialty_base_value"`
	SpecialtyCreatedAt   pgtype.Timestamptz `json:"specialty_created_at"`
	SpecialtyUpdatedAt   pgtype.Timestamptz `json:"specialty_updated_at"`
}

func (q *Queries) CreateCharacterSkill(ctx context.Context, arg CreateCharacterSkillParams) (CreateCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, createCharacterSkill,
		arg.Name,
		arg.CategoryID,
		arg.BaseValue,
		arg.Value,
		arg.Checked,
		arg.Specialized,
		arg.SpecialtyID,
		arg.UserID,
		arg.CharacterID,
	)
	var i CreateCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.CategoryID,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.Specialized,
		&i.SpecialtyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.SpecialtyPkID,
		&i.SpecialtyName,
		&i.SpecialtyDescription,
		&i.SpecialtyBaseValue,
		&i.SpecialtyCreatedAt,
		&i.SpecialtyUpdatedAt,
	)
	return i, err
}
