// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createDiceRoll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiceRoll = `-- name: CreateDiceRoll :one
INSERT INTO dice_rolls (character_id, user_id, expression, result, rolls, modifiers)
SELECT c.id, c.user_id, $1, $2, $3, $4
FROM characters c
WHERE c.id = $5
  AND c.user_id = $6
RETURNING id, character_id, user_id, expression, result, rolls, modifiers, created_at
`

type CreateDiceRollParams struct {
	Expression  string      `json:"expression"`
	Result      int32       `json:"result"`
	Rolls       []int32     `json:"rolls"`
	Modifiers   []int32     `json:"modifiers"`
	CharacterID pgtype.UUID `json:"character_id"`
	UserID      string      `json:"user_id"`
}

func (q *Queries) CreateDiceRoll(ctx context.Context, arg CreateDiceRollParams) (DiceRoll, error) {
	row := q.db.QueryRow(ctx, createDiceRoll,
		arg.Expression,
		arg.Result,
		arg.Rolls,
		arg.Modifiers,
		arg.CharacterID,
		arg.UserID,
	)
	var i DiceRoll
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.UserID,
		&i.Expression,
		&i.Result,
		&i.Rolls,
		&i.Modifiers,
		&i.CreatedAt,
	)
	return i, err
}
