// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createCharacter.sql

package db

import (
	"context"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    user_id,
    name,
    player_name,
    occupation,
    age,
    sex,
    residence,
    birthplace,
    portrait_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, name, player_name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_url
`

type CreateCharacterParams struct {
	UserID      string  `json:"user_id"`
	Name        string  `json:"name"`
	PlayerName  *string `json:"player_name"`
	Occupation  *string `json:"occupation"`
	Age         *int16  `json:"age"`
	Sex         *string `json:"sex"`
	Residence   *string `json:"residence"`
	Birthplace  *string `json:"birthplace"`
	PortraitUrl *string `json:"portrait_url"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.UserID,
		arg.Name,
		arg.PlayerName,
		arg.Occupation,
		arg.Age,
		arg.Sex,
		arg.Residence,
		arg.Birthplace,
		arg.PortraitUrl,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PlayerName,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitUrl,
	)
	return i, err
}
