// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacterSkill = `-- name: CreateCharacterSkill :one
WITH inserted AS (
    INSERT INTO skills (
        character_id,
        name,
        base_value,
        value,
        checked,
        is_protected,
        base_rule
    )
    SELECT
        c.id,
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    FROM characters c
    WHERE c.user_id = $7
      AND c.id = $8
    RETURNING id, character_id, name, base_value, value, checked, created_at, updated_at, is_protected, base_rule
)
SELECT id, character_id, name, base_value, value, checked, created_at, updated_at, is_protected, base_rule FROM inserted
`

type CreateCharacterSkillParams struct {
	Name        string      `json:"name"`
	BaseValue   int16       `json:"base_value"`
	Value       int16       `json:"value"`
	Checked     bool        `json:"checked"`
	IsProtected bool        `json:"is_protected"`
	BaseRule    *string     `json:"base_rule"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

type CreateCharacterSkillRow struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	Name        string             `json:"name"`
	BaseValue   int16              `json:"base_value"`
	Value       int16              `json:"value"`
	Checked     bool               `json:"checked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsProtected bool               `json:"is_protected"`
	BaseRule    *string            `json:"base_rule"`
}

func (q *Queries) CreateCharacterSkill(ctx context.Context, arg CreateCharacterSkillParams) (CreateCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, createCharacterSkill,
		arg.Name,
		arg.BaseValue,
		arg.Value,
		arg.Checked,
		arg.IsProtected,
		arg.BaseRule,
		arg.UserID,
		arg.CharacterID,
	)
	var i CreateCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
		&i.BaseRule,
	)
	return i, err
}
