// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createInventoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO character_inventory_items (
    character_id,
    name,
    quantity,
    category,
    description
)
SELECT
    character.id,
    $1,
    $2,
    $3,
    $4
FROM characters character
WHERE character.user_id = $5
  AND character.id = $6
RETURNING id, character_id, name, quantity, category, description, created_at, updated_at
`

type CreateInventoryItemParams struct {
	Name        string      `json:"name"`
	Quantity    *int32      `json:"quantity"`
	Category    *string     `json:"category"`
	Description *string     `json:"description"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (CharacterInventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.Name,
		arg.Quantity,
		arg.Category,
		arg.Description,
		arg.UserID,
		arg.CharacterID,
	)
	var i CharacterInventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Quantity,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
