// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createNote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    character_id,
    title,
    body
)
SELECT
    c.id,
    $1,
    $2
FROM characters c
WHERE c.user_id = $3
  AND c.id = $4
RETURNING id, character_id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.Title,
		arg.Body,
		arg.UserID,
		arg.CharacterID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
