// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createRoomEvent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoomEvent = `-- name: CreateRoomEvent :one
WITH next_sequence AS (
    UPDATE rooms
    SET event_sequence = event_sequence + 1
    WHERE id = $1
    RETURNING event_sequence
)
INSERT INTO room_events (room_id, actor_id, event_type, payload, sequence)
SELECT $1, $2, $3, $4, event_sequence
FROM next_sequence
RETURNING id, room_id, actor_id, event_type, payload, created_at, sequence
`

type CreateRoomEventParams struct {
	RoomID    pgtype.UUID `json:"room_id"`
	ActorID   string      `json:"actor_id"`
	EventType string      `json:"event_type"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) CreateRoomEvent(ctx context.Context, arg CreateRoomEventParams) (RoomEvent, error) {
	row := q.db.QueryRow(ctx, createRoomEvent,
		arg.RoomID,
		arg.ActorID,
		arg.EventType,
		arg.Payload,
	)
	var i RoomEvent
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ActorID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.Sequence,
	)
	return i, err
}
