// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createRoomMessage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoomMessage = `-- name: CreateRoomMessage :one
INSERT INTO room_messages (room_id, user_id, text)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1
    FROM room_members
    WHERE room_id = $1
      AND user_id = $2
)
RETURNING id, room_id, user_id, text, created_at
`

type CreateRoomMessageParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
	Text   string      `json:"text"`
}

func (q *Queries) CreateRoomMessage(ctx context.Context, arg CreateRoomMessageParams) (RoomMessage, error) {
	row := q.db.QueryRow(ctx, createRoomMessage, arg.RoomID, arg.UserID, arg.Text)
	var i RoomMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
