// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteBackstory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBackstory = `-- name: DeleteBackstory :one
DELETE FROM backstories b
USING characters c
WHERE c.id = b.character_id
  AND c.user_id = $1
  AND b.character_id = $2
RETURNING b.id, b.character_id, b.personal_description, b.created_at, b.updated_at
`

type DeleteBackstoryParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteBackstory(ctx context.Context, arg DeleteBackstoryParams) (Backstory, error) {
	row := q.db.QueryRow(ctx, deleteBackstory, arg.UserID, arg.CharacterID)
	var i Backstory
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.PersonalDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
