// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteMagicState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMagicState = `-- name: DeleteMagicState :one
DELETE FROM magic_states m
USING characters c
WHERE c.id = m.character_id
  AND c.user_id = $1
  AND m.character_id = $2
RETURNING m.id, m.character_id, m.max_mp, m.current_mp, m.created_at, m.updated_at
`

type DeleteMagicStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteMagicState(ctx context.Context, arg DeleteMagicStateParams) (MagicState, error) {
	row := q.db.QueryRow(ctx, deleteMagicState, arg.UserID, arg.CharacterID)
	var i MagicState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxMp,
		&i.CurrentMp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
