// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteRoomByID.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoomByID = `-- name: DeleteRoomByID :one
DELETE FROM rooms
WHERE id = $1
RETURNING id, owner_id, max_players, invite_token, created_at, updated_at, password_hash, last_activity_at
`

func (q *Queries) DeleteRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, deleteRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.LastActivityAt,
	)
	return i, err
}
