// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteRoom.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoom = `-- name: DeleteRoom :one
DELETE FROM rooms WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, max_players, created_at, updated_at
`

type DeleteRoomParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, deleteRoom, arg.ID, arg.OwnerID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
