// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteLuckState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLuckState = `-- name: DeleteLuckState :one
DELETE FROM luck_states l
USING characters c
WHERE c.id = l.character_id
  AND c.user_id = $1
  AND l.character_id = $2
RETURNING l.id, l.character_id, l.starting_luck, l.current_luck, l.created_at, l.updated_at
`

type DeleteLuckStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteLuckState(ctx context.Context, arg DeleteLuckStateParams) (LuckState, error) {
	row := q.db.QueryRow(ctx, deleteLuckState, arg.UserID, arg.CharacterID)
	var i LuckState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.StartingLuck,
		&i.CurrentLuck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
