// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteCharacteristics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCharacteristics = `-- name: DeleteCharacteristics :one
DELETE FROM characteristics ch
USING characters c
WHERE c.id = ch.character_id
  AND c.user_id = $1
  AND ch.character_id = $2
RETURNING ch.id, ch.character_id, ch.strength, ch.constitution, ch.size, ch.dexterity, ch.appearance, ch.intelligence, ch.power, ch.education, ch.created_at, ch.updated_at
`

type DeleteCharacteristicsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteCharacteristics(ctx context.Context, arg DeleteCharacteristicsParams) (Characteristic, error) {
	row := q.db.QueryRow(ctx, deleteCharacteristics, arg.UserID, arg.CharacterID)
	var i Characteristic
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Strength,
		&i.Constitution,
		&i.Size,
		&i.Dexterity,
		&i.Appearance,
		&i.Intelligence,
		&i.Power,
		&i.Education,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
