// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteHealthState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHealthState = `-- name: DeleteHealthState :one
DELETE FROM health_states h
USING characters c
WHERE c.id = h.character_id
  AND c.user_id = $1
  AND h.character_id = $2
RETURNING h.id, h.character_id, h.max_hp, h.current_hp, h.major_wound, h.unconscious, h.dying, h.dead, h.created_at, h.updated_at
`

type DeleteHealthStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteHealthState(ctx context.Context, arg DeleteHealthStateParams) (HealthState, error) {
	row := q.db.QueryRow(ctx, deleteHealthState, arg.UserID, arg.CharacterID)
	var i HealthState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MajorWound,
		&i.Unconscious,
		&i.Dying,
		&i.Dead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
