// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteUserByID.sql

package db

import (
	"context"
)

const deleteUserByClerkID = `-- name: DeleteUserByClerkID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByClerkID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserByClerkID, id)
	return err
}
