// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteAllRooms.sql

package db

import (
	"context"
)

const deleteAllRooms = `-- name: DeleteAllRooms :many
DELETE FROM rooms
RETURNING id, owner_id, max_players, invite_token, created_at, updated_at, password_hash, last_activity_at, name, event_sequence
`

func (q *Queries) DeleteAllRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, deleteAllRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.MaxPlayers,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.LastActivityAt,
			&i.Name,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
