// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteBackstoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBackstoryItem = `-- name: DeleteBackstoryItem :one
DELETE FROM backstory_items bi
USING backstories b, characters c
WHERE b.id = bi.backstory_id
  AND c.id = b.character_id
  AND c.user_id = $1
  AND b.character_id = $2
  AND bi.id = $3
RETURNING bi.id, bi.backstory_id, bi.section, bi.title, bi.text, bi.created_at, bi.updated_at
`

type DeleteBackstoryItemParams struct {
	UserID          string      `json:"user_id"`
	CharacterID     pgtype.UUID `json:"character_id"`
	BackstoryItemID pgtype.UUID `json:"backstory_item_id"`
}

func (q *Queries) DeleteBackstoryItem(ctx context.Context, arg DeleteBackstoryItemParams) (BackstoryItem, error) {
	row := q.db.QueryRow(ctx, deleteBackstoryItem, arg.UserID, arg.CharacterID, arg.BackstoryItemID)
	var i BackstoryItem
	err := row.Scan(
		&i.ID,
		&i.BackstoryID,
		&i.Section,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
