// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteDiceRoll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDiceRoll = `-- name: DeleteDiceRoll :one
DELETE FROM dice_rolls dr
USING characters c
WHERE c.id = dr.character_id
  AND c.user_id = $1
  AND dr.character_id = $2
  AND dr.id = $3
RETURNING dr.id, dr.character_id, dr.user_id, dr.expression, dr.result, dr.details, dr.created_at
`

type DeleteDiceRollParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	RollID      pgtype.UUID `json:"roll_id"`
}

func (q *Queries) DeleteDiceRoll(ctx context.Context, arg DeleteDiceRollParams) (DiceRoll, error) {
	row := q.db.QueryRow(ctx, deleteDiceRoll, arg.UserID, arg.CharacterID, arg.RollID)
	var i DiceRoll
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.UserID,
		&i.Expression,
		&i.Result,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}
