// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteUserByClerkID.sql

package db

import (
	"context"
)

const deleteUserByClerkID = `-- name: DeleteUserByClerkID :exec
DELETE FROM users
WHERE clerk_user_id = $1
`

func (q *Queries) DeleteUserByClerkID(ctx context.Context, clerkUserID string) error {
	_, err := q.db.Exec(ctx, deleteUserByClerkID, clerkUserID)
	return err
}
