// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteDerivedStats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDerivedStats = `-- name: DeleteDerivedStats :one
DELETE FROM derived_stats d
USING characters c
WHERE c.id = d.character_id
  AND c.user_id = $1
  AND d.character_id = $2
RETURNING d.id, d.character_id, d.speed, d.physique, d.damage_bonus, d.dodge_value, d.created_at, d.updated_at
`

type DeleteDerivedStatsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteDerivedStats(ctx context.Context, arg DeleteDerivedStatsParams) (DerivedStat, error) {
	row := q.db.QueryRow(ctx, deleteDerivedStats, arg.UserID, arg.CharacterID)
	var i DerivedStat
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Speed,
		&i.Physique,
		&i.DamageBonus,
		&i.DodgeValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
