// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE user_id = $1
  AND id = $2
`

type DeleteCharacterParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.Exec(ctx, deleteCharacter, arg.UserID, arg.ID)
	return err
}
