// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteInvalidRooms.sql

package db

import (
	"context"
)

const deleteInvalidRooms = `-- name: DeleteInvalidRooms :many
DELETE FROM rooms r
WHERE NOT EXISTS (
    SELECT 1
    FROM room_members rm
    WHERE rm.room_id = r.id
)
OR NOT EXISTS (
    SELECT 1
    FROM users u
    WHERE u.id = r.owner_id
)
OR NOT EXISTS (
    SELECT 1
    FROM room_members owner_member
    WHERE owner_member.room_id = r.id
      AND owner_member.user_id = r.owner_id
)
RETURNING id, owner_id, max_players, invite_token, created_at, updated_at, password_hash, last_activity_at, name
`

func (q *Queries) DeleteInvalidRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, deleteInvalidRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.MaxPlayers,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.LastActivityAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
