// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteNote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE character_id = $1 AND id = $2
`

type DeleteNoteParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.CharacterID, arg.ID)
	return err
}
