// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteSanityState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSanityState = `-- name: DeleteSanityState :one
DELETE FROM sanity_states s
USING characters c
WHERE c.id = s.character_id
  AND c.user_id = $1
  AND s.character_id = $2
RETURNING s.id, s.character_id, s.max_sanity, s.current_sanity, s.temp_insanity, s.indef_insanity, s.created_at, s.updated_at
`

type DeleteSanityStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteSanityState(ctx context.Context, arg DeleteSanityStateParams) (SanityState, error) {
	row := q.db.QueryRow(ctx, deleteSanityState, arg.UserID, arg.CharacterID)
	var i SanityState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxSanity,
		&i.CurrentSanity,
		&i.TempInsanity,
		&i.IndefInsanity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
