// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCharacter = `-- name: DeleteCharacter :one
DELETE FROM characters
WHERE user_id = $1
  AND id = $2
RETURNING id, user_id, name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_key
`

type DeleteCharacterParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, deleteCharacter, arg.UserID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitKey,
	)
	return i, err
}
