// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteFinances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFinances = `-- name: DeleteFinances :one
DELETE FROM finances f
USING characters c
WHERE c.id = f.character_id
  AND c.user_id = $1
  AND f.character_id = $2
RETURNING f.id, f.character_id, f.spending_limit, f.cash, f.assets, f.credit_rating_skill_id, f.created_at, f.updated_at
`

type DeleteFinancesParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) DeleteFinances(ctx context.Context, arg DeleteFinancesParams) (Finance, error) {
	row := q.db.QueryRow(ctx, deleteFinances, arg.UserID, arg.CharacterID)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.SpendingLimit,
		&i.Cash,
		&i.Assets,
		&i.CreditRatingSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
