// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getAllUserCharacterCards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllUserCharacterCards = `-- name: GetAllUserCharacterCards :many
SELECT
    c.id,
    c.name,
    c.occupation,
    c.age,
    c.sex,
    c.residence,
    c.portrait_url,
    COALESCE(h.current_hp, 0)::smallint AS current_hp,
    COALESCE(h.max_hp, 0)::smallint AS max_hp,
    COALESCE(m.current_mp, 0)::smallint AS current_mp,
    COALESCE(m.max_mp, 0)::smallint AS max_mp,
    COALESCE(s.current_sanity, 0)::smallint AS current_sanity,
    COALESCE(s.max_sanity, 0)::smallint AS max_sanity,
    COALESCE(l.current_luck, 0)::smallint AS current_luck,
    COALESCE(l.starting_luck, 0)::smallint AS starting_luck
FROM characters c
LEFT JOIN health_states h ON h.character_id = c.id
LEFT JOIN magic_states m ON m.character_id = c.id
LEFT JOIN sanity_states s ON s.character_id = c.id
LEFT JOIN luck_states l ON l.character_id = c.id
WHERE c.user_id = $1
ORDER BY c.created_at DESC
`

type GetAllUserCharacterCardsRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Occupation    *string     `json:"occupation"`
	Age           *int16      `json:"age"`
	Sex           *string     `json:"sex"`
	Residence     *string     `json:"residence"`
	PortraitUrl   *string     `json:"portrait_url"`
	CurrentHp     int16       `json:"current_hp"`
	MaxHp         int16       `json:"max_hp"`
	CurrentMp     int16       `json:"current_mp"`
	MaxMp         int16       `json:"max_mp"`
	CurrentSanity int16       `json:"current_sanity"`
	MaxSanity     int16       `json:"max_sanity"`
	CurrentLuck   int16       `json:"current_luck"`
	StartingLuck  int16       `json:"starting_luck"`
}

func (q *Queries) GetAllUserCharacterCards(ctx context.Context, userID string) ([]GetAllUserCharacterCardsRow, error) {
	rows, err := q.db.Query(ctx, getAllUserCharacterCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserCharacterCardsRow{}
	for rows.Next() {
		var i GetAllUserCharacterCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Occupation,
			&i.Age,
			&i.Sex,
			&i.Residence,
			&i.PortraitUrl,
			&i.CurrentHp,
			&i.MaxHp,
			&i.CurrentMp,
			&i.MaxMp,
			&i.CurrentSanity,
			&i.MaxSanity,
			&i.CurrentLuck,
			&i.StartingLuck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
