// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getBackstoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackstoryItem = `-- name: GetBackstoryItem :one
SELECT bi.id, bi.backstory_id, bi.section, bi.title, bi.text, bi.created_at, bi.updated_at
FROM backstory_items bi
JOIN backstories b ON b.id = bi.backstory_id
JOIN characters c ON c.id = b.character_id
WHERE c.user_id = $1
  AND b.character_id = $2
  AND bi.id = $3
`

type GetBackstoryItemParams struct {
	UserID          string      `json:"user_id"`
	CharacterID     pgtype.UUID `json:"character_id"`
	BackstoryItemID pgtype.UUID `json:"backstory_item_id"`
}

func (q *Queries) GetBackstoryItem(ctx context.Context, arg GetBackstoryItemParams) (BackstoryItem, error) {
	row := q.db.QueryRow(ctx, getBackstoryItem, arg.UserID, arg.CharacterID, arg.BackstoryItemID)
	var i BackstoryItem
	err := row.Scan(
		&i.ID,
		&i.BackstoryID,
		&i.Section,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
