// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getBackstoryItems.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackstoryItems = `-- name: GetBackstoryItems :many
SELECT bi.id, bi.backstory_id, bi.section, bi.title, bi.text, bi.created_at, bi.updated_at
FROM backstory_items bi
JOIN backstories b ON b.id = bi.backstory_id
JOIN characters c ON c.id = b.character_id
WHERE c.user_id = $1
  AND b.character_id = $2
ORDER BY bi.created_at
`

type GetBackstoryItemsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetBackstoryItems(ctx context.Context, arg GetBackstoryItemsParams) ([]BackstoryItem, error) {
	rows, err := q.db.Query(ctx, getBackstoryItems, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackstoryItem{}
	for rows.Next() {
		var i BackstoryItem
		if err := rows.Scan(
			&i.ID,
			&i.BackstoryID,
			&i.Section,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
