// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getBackstoryByCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackstoryByCharacter = `-- name: GetBackstoryByCharacter :one
SELECT b.id, b.character_id, b.personal_description, b.created_at, b.updated_at
FROM backstories b
JOIN characters c ON c.id = b.character_id
WHERE c.user_id = $1
  AND b.character_id = $2
`

type GetBackstoryByCharacterParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetBackstoryByCharacter(ctx context.Context, arg GetBackstoryByCharacterParams) (Backstory, error) {
	row := q.db.QueryRow(ctx, getBackstoryByCharacter, arg.UserID, arg.CharacterID)
	var i Backstory
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.PersonalDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
