// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacter = `-- name: GetCharacter :one
SELECT id, user_id, name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_key
FROM characters
WHERE user_id = $1 AND id = $2
`

type GetCharacterParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetCharacter(ctx context.Context, arg GetCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, arg.UserID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitKey,
	)
	return i, err
}
