// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacteristics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacteristics = `-- name: GetCharacteristics :one
SELECT ch.id, ch.character_id, ch.strength, ch.constitution, ch.size, ch.dexterity, ch.appearance, ch.intelligence, ch.power, ch.education, ch.created_at, ch.updated_at FROM characteristics ch
JOIN characters c ON c.id = ch.character_id
WHERE c.user_id = $1
  AND ch.character_id = $2
`

type GetCharacteristicsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetCharacteristics(ctx context.Context, arg GetCharacteristicsParams) (Characteristic, error) {
	row := q.db.QueryRow(ctx, getCharacteristics, arg.UserID, arg.CharacterID)
	var i Characteristic
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Strength,
		&i.Constitution,
		&i.Size,
		&i.Dexterity,
		&i.Appearance,
		&i.Intelligence,
		&i.Power,
		&i.Education,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
