// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterAdditionalData.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackstory = `-- name: GetBackstory :one
SELECT id, character_id, personal_description, created_at, updated_at FROM backstories WHERE character_id = $1
`

func (q *Queries) GetBackstory(ctx context.Context, characterID pgtype.UUID) (Backstory, error) {
	row := q.db.QueryRow(ctx, getBackstory, characterID)
	var i Backstory
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.PersonalDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackstoryItemsByBackstoryID = `-- name: GetBackstoryItemsByBackstoryID :many
SELECT id, backstory_id, section, title, text, created_at, updated_at FROM backstory_items WHERE backstory_id = $1
ORDER BY created_at
`

func (q *Queries) GetBackstoryItemsByBackstoryID(ctx context.Context, backstoryID pgtype.UUID) ([]BackstoryItem, error) {
	rows, err := q.db.Query(ctx, getBackstoryItemsByBackstoryID, backstoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackstoryItem{}
	for rows.Next() {
		var i BackstoryItem
		if err := rows.Scan(
			&i.ID,
			&i.BackstoryID,
			&i.Section,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDerivedStats = `-- name: GetDerivedStats :one
SELECT id, character_id, speed, physique, damage_bonus, dodge_value, created_at, updated_at FROM derived_stats WHERE character_id = $1
`

func (q *Queries) GetDerivedStats(ctx context.Context, characterID pgtype.UUID) (DerivedStat, error) {
	row := q.db.QueryRow(ctx, getDerivedStats, characterID)
	var i DerivedStat
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Speed,
		&i.Physique,
		&i.DamageBonus,
		&i.DodgeValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkills = `-- name: GetSkills :many
SELECT s.id, s.character_id, s.name, s.category_id, s.base_value, s.value, s.checked, s.specialized, s.specialty_id, s.created_at, s.updated_at,
    sc.name as category_name,
    ss.id as specialty_pk_id,
    ss.name as specialty_name,
    ss.description as specialty_description,
    ss.base_value as specialty_base_value,
    ss.created_at as specialty_created_at,
    ss.updated_at as specialty_updated_at
FROM skills s
JOIN skills_categories sc ON s.category_id = sc.id
LEFT JOIN skills_specialties ss ON s.specialty_id = ss.id
WHERE s.character_id = $1
ORDER BY s.name
`

type GetSkillsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CharacterID          pgtype.UUID        `json:"character_id"`
	Name                 string             `json:"name"`
	CategoryID           pgtype.UUID        `json:"category_id"`
	BaseValue            int16              `json:"base_value"`
	Value                int16              `json:"value"`
	Checked              bool               `json:"checked"`
	Specialized          bool               `json:"specialized"`
	SpecialtyID          pgtype.UUID        `json:"specialty_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CategoryName         string             `json:"category_name"`
	SpecialtyPkID        pgtype.UUID        `json:"specialty_pk_id"`
	SpecialtyName        *string            `json:"specialty_name"`
	SpecialtyDescription *string            `json:"specialty_description"`
	SpecialtyBaseValue   *int16             `json:"specialty_base_value"`
	SpecialtyCreatedAt   pgtype.Timestamptz `json:"specialty_created_at"`
	SpecialtyUpdatedAt   pgtype.Timestamptz `json:"specialty_updated_at"`
}

func (q *Queries) GetSkills(ctx context.Context, characterID pgtype.UUID) ([]GetSkillsRow, error) {
	rows, err := q.db.Query(ctx, getSkills, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSkillsRow{}
	for rows.Next() {
		var i GetSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.CategoryID,
			&i.BaseValue,
			&i.Value,
			&i.Checked,
			&i.Specialized,
			&i.SpecialtyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.SpecialtyPkID,
			&i.SpecialtyName,
			&i.SpecialtyDescription,
			&i.SpecialtyBaseValue,
			&i.SpecialtyCreatedAt,
			&i.SpecialtyUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
