// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterNotes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterNotes = `-- name: GetCharacterNotes :many
SELECT n.id, n.character_id, n.title, n.body, n.created_at, n.updated_at
FROM notes n
JOIN characters c ON c.id = n.character_id
WHERE c.user_id = $1
  AND n.character_id = $2
ORDER BY n.created_at DESC
`

type GetCharacterNotesParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetCharacterNotes(ctx context.Context, arg GetCharacterNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getCharacterNotes, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
