// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterAdditionalData.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackstory = `-- name: GetBackstory :one
SELECT id, character_id, personal_description, created_at, updated_at FROM backstories WHERE character_id = $1
`

func (q *Queries) GetBackstory(ctx context.Context, characterID pgtype.UUID) (Backstory, error) {
	row := q.db.QueryRow(ctx, getBackstory, characterID)
	var i Backstory
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.PersonalDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackstoryItemsByBackstoryID = `-- name: GetBackstoryItemsByBackstoryID :many
SELECT id, backstory_id, section, title, text, created_at, updated_at FROM backstory_items WHERE backstory_id = $1
ORDER BY created_at
`

func (q *Queries) GetBackstoryItemsByBackstoryID(ctx context.Context, backstoryID pgtype.UUID) ([]BackstoryItem, error) {
	rows, err := q.db.Query(ctx, getBackstoryItemsByBackstoryID, backstoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackstoryItem{}
	for rows.Next() {
		var i BackstoryItem
		if err := rows.Scan(
			&i.ID,
			&i.BackstoryID,
			&i.Section,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkills = `-- name: GetSkills :many
SELECT s.id, s.character_id, s.name, s.base_value, s.value, s.checked, s.created_at, s.updated_at, s.is_protected, s.base_rule
FROM skills s
WHERE s.character_id = $1
ORDER BY s.name
`

func (q *Queries) GetSkills(ctx context.Context, characterID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkills, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.BaseValue,
			&i.Value,
			&i.Checked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsProtected,
			&i.BaseRule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
