// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterNote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterNote = `-- name: GetCharacterNote :one
SELECT id, character_id, title, body, created_at, updated_at
FROM notes
WHERE character_id = $1 AND id = $2
`

type GetCharacterNoteParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetCharacterNote(ctx context.Context, arg GetCharacterNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getCharacterNote, arg.CharacterID, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
