// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterSkill = `-- name: GetCharacterSkill :one
SELECT s.id, s.character_id, s.name, s.category_id, s.base_value, s.value, s.checked, s.specialized, s.specialty_id, s.created_at, s.updated_at,
    sc.name as category_name,
    ss.id as specialty_pk_id,
    ss.name as specialty_name,
    ss.description as specialty_description,
    ss.base_value as specialty_base_value,
    ss.created_at as specialty_created_at,
    ss.updated_at as specialty_updated_at
FROM skills s
JOIN characters c ON c.id = s.character_id
JOIN skills_categories sc ON s.category_id = sc.id
LEFT JOIN skills_specialties ss ON s.specialty_id = ss.id
WHERE c.user_id = $1
  AND s.character_id = $2
  AND s.id = $3
`

type GetCharacterSkillParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	SkillID     pgtype.UUID `json:"skill_id"`
}

type GetCharacterSkillRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CharacterID          pgtype.UUID        `json:"character_id"`
	Name                 string             `json:"name"`
	CategoryID           pgtype.UUID        `json:"category_id"`
	BaseValue            int16              `json:"base_value"`
	Value                int16              `json:"value"`
	Checked              bool               `json:"checked"`
	Specialized          bool               `json:"specialized"`
	SpecialtyID          pgtype.UUID        `json:"specialty_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CategoryName         string             `json:"category_name"`
	SpecialtyPkID        pgtype.UUID        `json:"specialty_pk_id"`
	SpecialtyName        *string            `json:"specialty_name"`
	SpecialtyDescription *string            `json:"specialty_description"`
	SpecialtyBaseValue   *int16             `json:"specialty_base_value"`
	SpecialtyCreatedAt   pgtype.Timestamptz `json:"specialty_created_at"`
	SpecialtyUpdatedAt   pgtype.Timestamptz `json:"specialty_updated_at"`
}

func (q *Queries) GetCharacterSkill(ctx context.Context, arg GetCharacterSkillParams) (GetCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, getCharacterSkill, arg.UserID, arg.CharacterID, arg.SkillID)
	var i GetCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.CategoryID,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.Specialized,
		&i.SpecialtyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.SpecialtyPkID,
		&i.SpecialtyName,
		&i.SpecialtyDescription,
		&i.SpecialtyBaseValue,
		&i.SpecialtyCreatedAt,
		&i.SpecialtyUpdatedAt,
	)
	return i, err
}
