// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterSkills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterSkills = `-- name: GetCharacterSkills :many
SELECT s.id, s.character_id, s.name, s.base_value, s.value, s.checked, s.created_at, s.updated_at, s.is_protected, s.base_rule
FROM skills s
JOIN characters c ON c.id = s.character_id
WHERE c.user_id = $1
  AND s.character_id = $2
ORDER BY s.name
`

type GetCharacterSkillsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetCharacterSkills(ctx context.Context, arg GetCharacterSkillsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getCharacterSkills, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.BaseValue,
			&i.Value,
			&i.Checked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsProtected,
			&i.BaseRule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
