// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterSkill = `-- name: GetCharacterSkill :one
SELECT s.id, s.character_id, s.name, s.base_value, s.value, s.checked, s.created_at, s.updated_at, s.is_protected, s.base_rule
FROM skills s
JOIN characters c ON c.id = s.character_id
WHERE c.user_id = $1
  AND s.character_id = $2
  AND s.id = $3
`

type GetCharacterSkillParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	SkillID     pgtype.UUID `json:"skill_id"`
}

func (q *Queries) GetCharacterSkill(ctx context.Context, arg GetCharacterSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getCharacterSkill, arg.UserID, arg.CharacterID, arg.SkillID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
		&i.BaseRule,
	)
	return i, err
}
