// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterSkill = `-- name: GetCharacterSkill :one
SELECT s.id, s.character_id, s.name, s.category_id, s.base_value, s.value, s.checked, s.created_at, s.updated_at, s.is_protected, s.base_rule,
    sc.name as category_name
FROM skills s
JOIN characters c ON c.id = s.character_id
JOIN skills_categories sc ON s.category_id = sc.id
WHERE c.user_id = $1
  AND s.character_id = $2
  AND s.id = $3
`

type GetCharacterSkillParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	SkillID     pgtype.UUID `json:"skill_id"`
}

type GetCharacterSkillRow struct {
	ID           pgtype.UUID        `json:"id"`
	CharacterID  pgtype.UUID        `json:"character_id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	BaseValue    int16              `json:"base_value"`
	Value        int16              `json:"value"`
	Checked      bool               `json:"checked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsProtected  bool               `json:"is_protected"`
	BaseRule     *string            `json:"base_rule"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) GetCharacterSkill(ctx context.Context, arg GetCharacterSkillParams) (GetCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, getCharacterSkill, arg.UserID, arg.CharacterID, arg.SkillID)
	var i GetCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.CategoryID,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
		&i.BaseRule,
		&i.CategoryName,
	)
	return i, err
}
