// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getCharacterNotes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterNotes = `-- name: GetCharacterNotes :many
SELECT id, character_id, title, body, created_at, updated_at
FROM notes
WHERE character_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCharacterNotes(ctx context.Context, characterID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, getCharacterNotes, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
