// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getDiceRolls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDiceRolls = `-- name: GetDiceRolls :many
SELECT dr.id, dr.character_id, dr.user_id, dr.expression, dr.result, dr.details, dr.created_at
FROM dice_rolls dr
JOIN characters c ON c.id = dr.character_id
WHERE c.user_id = $1
  AND dr.character_id = $2
ORDER BY dr.created_at DESC
LIMIT 50
`

type GetDiceRollsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetDiceRolls(ctx context.Context, arg GetDiceRollsParams) ([]DiceRoll, error) {
	rows, err := q.db.Query(ctx, getDiceRolls, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiceRoll{}
	for rows.Next() {
		var i DiceRoll
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.UserID,
			&i.Expression,
			&i.Result,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
