// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getDiceRoll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDiceRoll = `-- name: GetDiceRoll :one
SELECT dr.id, dr.character_id, dr.user_id, dr.expression, dr.result, dr.rolls, dr.modifiers, dr.created_at
FROM dice_rolls dr
JOIN characters c ON c.id = dr.character_id
WHERE c.user_id = $1
  AND dr.character_id = $2
  AND dr.id = $3
`

type GetDiceRollParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	RollID      pgtype.UUID `json:"roll_id"`
}

func (q *Queries) GetDiceRoll(ctx context.Context, arg GetDiceRollParams) (DiceRoll, error) {
	row := q.db.QueryRow(ctx, getDiceRoll, arg.UserID, arg.CharacterID, arg.RollID)
	var i DiceRoll
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.UserID,
		&i.Expression,
		&i.Result,
		&i.Rolls,
		&i.Modifiers,
		&i.CreatedAt,
	)
	return i, err
}
