// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getDerivedStats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDerivedStats = `-- name: GetDerivedStats :one
SELECT d.id, d.character_id, d.speed, d.physique, d.damage_bonus, d.dodge_value, d.created_at, d.updated_at FROM derived_stats d
JOIN characters c ON c.id = d.character_id
WHERE c.user_id = $1
  AND d.character_id = $2
`

type GetDerivedStatsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetDerivedStats(ctx context.Context, arg GetDerivedStatsParams) (DerivedStat, error) {
	row := q.db.QueryRow(ctx, getDerivedStats, arg.UserID, arg.CharacterID)
	var i DerivedStat
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Speed,
		&i.Physique,
		&i.DamageBonus,
		&i.DodgeValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
