// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getFinances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFinances = `-- name: GetFinances :one
SELECT f.id, f.character_id, f.spending_limit, f.cash, f.assets, f.credit_rating_skill_id, f.created_at, f.updated_at FROM finances f
JOIN characters c ON c.id = f.character_id
WHERE c.user_id = $1
  AND f.character_id = $2
`

type GetFinancesParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetFinances(ctx context.Context, arg GetFinancesParams) (Finance, error) {
	row := q.db.QueryRow(ctx, getFinances, arg.UserID, arg.CharacterID)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.SpendingLimit,
		&i.Cash,
		&i.Assets,
		&i.CreditRatingSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
