// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getHealthState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHealthState = `-- name: GetHealthState :one
SELECT h.id, h.character_id, h.max_hp, h.current_hp, h.major_wound, h.unconscious, h.dying, h.dead, h.created_at, h.updated_at FROM health_states h
JOIN characters c ON c.id = h.character_id
WHERE c.user_id = $1
  AND h.character_id = $2
`

type GetHealthStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetHealthState(ctx context.Context, arg GetHealthStateParams) (HealthState, error) {
	row := q.db.QueryRow(ctx, getHealthState, arg.UserID, arg.CharacterID)
	var i HealthState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MajorWound,
		&i.Unconscious,
		&i.Dying,
		&i.Dead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
