// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getInventoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT inventory_item.id, inventory_item.character_id, inventory_item.name, inventory_item.quantity, inventory_item.category, inventory_item.description, inventory_item.created_at, inventory_item.updated_at
FROM character_inventory_items inventory_item
JOIN characters character ON character.id = inventory_item.character_id
WHERE character.user_id = $1
  AND inventory_item.character_id = $2
  AND inventory_item.id = $3
`

type GetInventoryItemParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	ItemID      pgtype.UUID `json:"item_id"`
}

func (q *Queries) GetInventoryItem(ctx context.Context, arg GetInventoryItemParams) (CharacterInventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, arg.UserID, arg.CharacterID, arg.ItemID)
	var i CharacterInventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Quantity,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
