// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getInventoryItems.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryItems = `-- name: GetInventoryItems :many
SELECT inventory_item.id, inventory_item.character_id, inventory_item.name, inventory_item.quantity, inventory_item.category, inventory_item.description, inventory_item.created_at, inventory_item.updated_at
FROM character_inventory_items inventory_item
JOIN characters character ON character.id = inventory_item.character_id
WHERE character.user_id = $1
  AND inventory_item.character_id = $2
ORDER BY inventory_item.created_at DESC, inventory_item.id DESC
`

type GetInventoryItemsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetInventoryItems(ctx context.Context, arg GetInventoryItemsParams) ([]CharacterInventoryItem, error) {
	rows, err := q.db.Query(ctx, getInventoryItems, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterInventoryItem{}
	for rows.Next() {
		var i CharacterInventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Quantity,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
