// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getLuckState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLuckState = `-- name: GetLuckState :one
SELECT l.id, l.character_id, l.starting_luck, l.current_luck, l.created_at, l.updated_at FROM luck_states l
JOIN characters c ON c.id = l.character_id
WHERE c.user_id = $1
  AND l.character_id = $2
`

type GetLuckStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetLuckState(ctx context.Context, arg GetLuckStateParams) (LuckState, error) {
	row := q.db.QueryRow(ctx, getLuckState, arg.UserID, arg.CharacterID)
	var i LuckState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.StartingLuck,
		&i.CurrentLuck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
