// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getMagicState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMagicState = `-- name: GetMagicState :one
SELECT m.id, m.character_id, m.max_mp, m.current_mp, m.created_at, m.updated_at FROM magic_states m
JOIN characters c ON c.id = m.character_id
WHERE c.user_id = $1
  AND m.character_id = $2
`

type GetMagicStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetMagicState(ctx context.Context, arg GetMagicStateParams) (MagicState, error) {
	row := q.db.QueryRow(ctx, getMagicState, arg.UserID, arg.CharacterID)
	var i MagicState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxMp,
		&i.CurrentMp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
