// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getNextRoomOwner.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNextRoomOwner = `-- name: GetNextRoomOwner :one
SELECT id, room_id, user_id, character_id, role, joined_at
FROM room_members
WHERE room_id = $1
ORDER BY joined_at ASC, id ASC
LIMIT 1
`

func (q *Queries) GetNextRoomOwner(ctx context.Context, roomID pgtype.UUID) (RoomMember, error) {
	row := q.db.QueryRow(ctx, getNextRoomOwner, roomID)
	var i RoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
