// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRoomMetaData.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomMetaData = `-- name: GetRoomMetaData :one
SELECT id, max_players
FROM rooms
WHERE id = $1 AND invite_token = $2
FOR UPDATE
`

type GetRoomMetaDataParams struct {
	ID          pgtype.UUID `json:"id"`
	InviteToken string      `json:"invite_token"`
}

type GetRoomMetaDataRow struct {
	ID         pgtype.UUID `json:"id"`
	MaxPlayers int32       `json:"max_players"`
}

func (q *Queries) GetRoomMetaData(ctx context.Context, arg GetRoomMetaDataParams) (GetRoomMetaDataRow, error) {
	row := q.db.QueryRow(ctx, getRoomMetaData, arg.ID, arg.InviteToken)
	var i GetRoomMetaDataRow
	err := row.Scan(&i.ID, &i.MaxPlayers)
	return i, err
}
