// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRoomByID.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomByID = `-- name: GetRoomByID :one
SELECT r.id, r.owner_id, r.max_players, r.invite_token, r.created_at, r.updated_at, r.password_hash, r.last_activity_at, r.name FROM rooms r
WHERE r.id = $1
  AND EXISTS (SELECT 1 FROM room_members WHERE room_id = $1 AND user_id = $2)
`

type GetRoomByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetRoomByID(ctx context.Context, arg GetRoomByIDParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, arg.ID, arg.UserID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.LastActivityAt,
		&i.Name,
	)
	return i, err
}
