// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRoomMembersCount.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomMembersCount = `-- name: GetRoomMembersCount :one
SELECT COUNT(*)::int FROM room_members rm
WHERE rm.room_id = $1
  AND EXISTS (SELECT 1 FROM room_members m WHERE m.room_id = $1 AND m.user_id = $2)
`

type GetRoomMembersCountParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetRoomMembersCount(ctx context.Context, arg GetRoomMembersCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getRoomMembersCount, arg.RoomID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
