// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRoomMembersCount.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomMembersCount = `-- name: GetRoomMembersCount :one
SELECT COUNT(*)::int FROM room_members WHERE room_id = $1
`

func (q *Queries) GetRoomMembersCount(ctx context.Context, roomID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getRoomMembersCount, roomID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
