// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRoomJoinMetaData.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomJoinMetaData = `-- name: GetRoomJoinMetaData :one
SELECT id, max_players, invite_token, password_hash
FROM rooms
WHERE id = $1
FOR UPDATE
`

type GetRoomJoinMetaDataRow struct {
	ID           pgtype.UUID `json:"id"`
	MaxPlayers   int32       `json:"max_players"`
	InviteToken  string      `json:"invite_token"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetRoomJoinMetaData(ctx context.Context, id pgtype.UUID) (GetRoomJoinMetaDataRow, error) {
	row := q.db.QueryRow(ctx, getRoomJoinMetaData, id)
	var i GetRoomJoinMetaDataRow
	err := row.Scan(
		&i.ID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.PasswordHash,
	)
	return i, err
}
