// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getSanityState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSanityState = `-- name: GetSanityState :one
SELECT s.id, s.character_id, s.max_sanity, s.current_sanity, s.temp_insanity, s.indef_insanity, s.created_at, s.updated_at FROM sanity_states s
JOIN characters c ON c.id = s.character_id
WHERE c.user_id = $1
  AND s.character_id = $2
`

type GetSanityStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) GetSanityState(ctx context.Context, arg GetSanityStateParams) (SanityState, error) {
	row := q.db.QueryRow(ctx, getSanityState, arg.UserID, arg.CharacterID)
	var i SanityState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxSanity,
		&i.CurrentSanity,
		&i.TempInsanity,
		&i.IndefInsanity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
