// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getUserByID.sql

package db

import (
	"context"
)

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, username, email, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
