// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listCharacterChangedRoomEventRecipients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCharacterChangedRoomEventRecipients = `-- name: ListCharacterChangedRoomEventRecipients :many
SELECT DISTINCT user_id
FROM room_members
WHERE room_id = $1
  AND (role = 'gm' OR character_id = $2)
ORDER BY user_id
`

type ListCharacterChangedRoomEventRecipientsParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) ListCharacterChangedRoomEventRecipients(ctx context.Context, arg ListCharacterChangedRoomEventRecipientsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listCharacterChangedRoomEventRecipients, arg.RoomID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
