// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listCharactersByUserID.sql

package db

import (
	"context"
)

const listCharactersByUserID = `-- name: ListCharactersByUserID :many
SELECT id, user_id, name, player_name, occupation, age, sex, residence, birthplace, created_at, updated_at
FROM characters
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCharactersByUserID(ctx context.Context, userID string) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PlayerName,
			&i.Occupation,
			&i.Age,
			&i.Sex,
			&i.Residence,
			&i.Birthplace,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
