// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listRoomIDsBySelectedCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoomIDsBySelectedCharacter = `-- name: ListRoomIDsBySelectedCharacter :many
SELECT room_id
FROM room_members
WHERE character_id = $1
ORDER BY room_id
`

func (q *Queries) ListRoomIDsBySelectedCharacter(ctx context.Context, characterID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRoomIDsBySelectedCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var room_id pgtype.UUID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
