// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listRooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRooms = `-- name: ListRooms :many
SELECT
    r.id,
    r.name,
    r.max_players,
    COUNT(rm.id)::int AS member_count,
    r.created_at,
    EXISTS (
        SELECT 1
        FROM room_members current_member
        WHERE current_member.room_id = r.id
          AND current_member.user_id = $1
    ) AS is_member
FROM rooms r
LEFT JOIN room_members rm ON rm.room_id = r.id
WHERE EXISTS (
    SELECT 1
    FROM room_members owner_member
    WHERE owner_member.room_id = r.id
      AND owner_member.user_id = r.owner_id
)
GROUP BY r.id
HAVING COUNT(rm.id) < r.max_players
    OR EXISTS (
        SELECT 1
        FROM room_members current_member
        WHERE current_member.room_id = r.id
          AND current_member.user_id = $1
    )
ORDER BY r.created_at DESC, r.id DESC
`

type ListRoomsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	MaxPlayers  int32              `json:"max_players"`
	MemberCount int32              `json:"member_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IsMember    bool               `json:"is_member"`
}

func (q *Queries) ListRooms(ctx context.Context, userID string) ([]ListRoomsRow, error) {
	rows, err := q.db.Query(ctx, listRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsRow{}
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxPlayers,
			&i.MemberCount,
			&i.CreatedAt,
			&i.IsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
