// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listRoomEvents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoomEvents = `-- name: ListRoomEvents :many
SELECT re.id, re.room_id, re.actor_id, re.event_type, re.payload, re.created_at
FROM room_events re
WHERE re.room_id = $1
  AND EXISTS (
      SELECT 1
      FROM room_members rm
      WHERE rm.room_id = re.room_id
        AND rm.user_id = $2
  )
ORDER BY re.created_at ASC, re.id ASC
LIMIT $3
`

type ListRoomEventsParams struct {
	RoomID     pgtype.UUID `json:"room_id"`
	UserID     string      `json:"user_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListRoomEvents(ctx context.Context, arg ListRoomEventsParams) ([]RoomEvent, error) {
	rows, err := q.db.Query(ctx, listRoomEvents, arg.RoomID, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomEvent{}
	for rows.Next() {
		var i RoomEvent
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.ActorID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
