// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listVisibleSelectedRoomMembers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listVisibleSelectedRoomMembers = `-- name: ListVisibleSelectedRoomMembers :many
WITH requester AS (
    SELECT role
    FROM room_members
    WHERE room_id = $1 AND user_id = $2
)
SELECT rm.id, rm.room_id, rm.user_id, rm.character_id, rm.role, rm.joined_at
FROM room_members rm
JOIN requester req ON TRUE
WHERE rm.room_id = $1
  AND rm.character_id IS NOT NULL
  AND (req.role = 'gm' OR rm.user_id = $2)
ORDER BY rm.joined_at, rm.id
`

type ListVisibleSelectedRoomMembersParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) ListVisibleSelectedRoomMembers(ctx context.Context, arg ListVisibleSelectedRoomMembersParams) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listVisibleSelectedRoomMembers, arg.RoomID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomMember{}
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.CharacterID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
