// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listPortraitKeys.sql

package db

import (
	"context"
)

const listCharacterPortraitKeys = `-- name: ListCharacterPortraitKeys :many
SELECT portrait_key
FROM characters
WHERE portrait_key IS NOT NULL
`

func (q *Queries) ListCharacterPortraitKeys(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, listCharacterPortraitKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var portrait_key *string
		if err := rows.Scan(&portrait_key); err != nil {
			return nil, err
		}
		items = append(items, portrait_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
