// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listRoomDiceRolls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoomDiceRolls = `-- name: ListRoomDiceRolls :many
SELECT
    rdr.id,
    rdr.room_id,
    rdr.dice_roll_id,
    rdr.user_id,
    rdr.kind,
    rdr.metadata,
    rdr.created_at,
    dr.character_id,
    dr.expression,
    dr.result,
    dr.details,
    dr.created_at AS dice_roll_created_at
FROM room_dice_rolls rdr
JOIN dice_rolls dr ON dr.id = rdr.dice_roll_id
WHERE rdr.room_id = $1
  AND EXISTS (
      SELECT 1
      FROM room_members m
      WHERE m.room_id = $1
        AND m.user_id = $2
  )
ORDER BY rdr.created_at DESC
LIMIT $3
`

type ListRoomDiceRollsParams struct {
	RoomID     pgtype.UUID `json:"room_id"`
	UserID     string      `json:"user_id"`
	LimitCount int32       `json:"limit_count"`
}

type ListRoomDiceRollsRow struct {
	ID                pgtype.UUID        `json:"id"`
	RoomID            pgtype.UUID        `json:"room_id"`
	DiceRollID        pgtype.UUID        `json:"dice_roll_id"`
	UserID            string             `json:"user_id"`
	Kind              string             `json:"kind"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CharacterID       pgtype.UUID        `json:"character_id"`
	Expression        string             `json:"expression"`
	Result            int32              `json:"result"`
	Details           []byte             `json:"details"`
	DiceRollCreatedAt pgtype.Timestamptz `json:"dice_roll_created_at"`
}

func (q *Queries) ListRoomDiceRolls(ctx context.Context, arg ListRoomDiceRollsParams) ([]ListRoomDiceRollsRow, error) {
	rows, err := q.db.Query(ctx, listRoomDiceRolls, arg.RoomID, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomDiceRollsRow{}
	for rows.Next() {
		var i ListRoomDiceRollsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.DiceRollID,
			&i.UserID,
			&i.Kind,
			&i.Metadata,
			&i.CreatedAt,
			&i.CharacterID,
			&i.Expression,
			&i.Result,
			&i.Details,
			&i.DiceRollCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
