// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listMembersByRoomID.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMembersByRoomID = `-- name: ListMembersByRoomID :many
SELECT rm.id, rm.room_id, rm.user_id, rm.character_id, rm.role, rm.joined_at FROM room_members rm
WHERE rm.room_id = $1
  AND EXISTS (SELECT 1 FROM room_members m WHERE m.room_id = $1 AND m.user_id = $2)
ORDER BY rm.joined_at
`

type ListMembersByRoomIDParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) ListMembersByRoomID(ctx context.Context, arg ListMembersByRoomIDParams) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listMembersByRoomID, arg.RoomID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomMember{}
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.CharacterID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
