// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listRoomMessages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoomMessages = `-- name: ListRoomMessages :many
SELECT rm.id, rm.room_id, rm.user_id, rm.text, rm.created_at
FROM room_messages rm
WHERE rm.room_id = $1
  AND EXISTS (
      SELECT 1
      FROM room_members m
      WHERE m.room_id = $1
        AND m.user_id = $2
  )
ORDER BY rm.created_at DESC
LIMIT $3
`

type ListRoomMessagesParams struct {
	RoomID     pgtype.UUID `json:"room_id"`
	UserID     string      `json:"user_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListRoomMessages(ctx context.Context, arg ListRoomMessagesParams) ([]RoomMessage, error) {
	rows, err := q.db.Query(ctx, listRoomMessages, arg.RoomID, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomMessage{}
	for rows.Next() {
		var i RoomMessage
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
