// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Backstory struct {
	ID                  pgtype.UUID        `json:"id"`
	CharacterID         pgtype.UUID        `json:"character_id"`
	PersonalDescription *string            `json:"personal_description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BackstoryItem struct {
	ID          pgtype.UUID        `json:"id"`
	BackstoryID pgtype.UUID        `json:"backstory_id"`
	Section     string             `json:"section"`
	Title       string             `json:"title"`
	Text        string             `json:"text"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Character struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	PlayerName  *string            `json:"player_name"`
	Occupation  *string            `json:"occupation"`
	Age         *int16             `json:"age"`
	Sex         *string            `json:"sex"`
	Residence   *string            `json:"residence"`
	Birthplace  *string            `json:"birthplace"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PortraitKey *string            `json:"portrait_key"`
}

type Characteristic struct {
	ID           pgtype.UUID        `json:"id"`
	CharacterID  pgtype.UUID        `json:"character_id"`
	Strength     *int16             `json:"strength"`
	Constitution *int16             `json:"constitution"`
	Size         *int16             `json:"size"`
	Dexterity    *int16             `json:"dexterity"`
	Appearance   *int16             `json:"appearance"`
	Intelligence *int16             `json:"intelligence"`
	Power        *int16             `json:"power"`
	Education    *int16             `json:"education"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DerivedStat struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	Speed       *int16             `json:"speed"`
	Physique    *int16             `json:"physique"`
	DamageBonus *string            `json:"damage_bonus"`
	DodgeValue  *int16             `json:"dodge_value"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DiceRoll struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	UserID      string             `json:"user_id"`
	Expression  string             `json:"expression"`
	Result      int32              `json:"result"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Finance struct {
	ID                  pgtype.UUID        `json:"id"`
	CharacterID         pgtype.UUID        `json:"character_id"`
	SpendingLimit       *string            `json:"spending_limit"`
	Cash                *string            `json:"cash"`
	Assets              *string            `json:"assets"`
	CreditRatingSkillID pgtype.UUID        `json:"credit_rating_skill_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type HealthState struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	MaxHp       int16              `json:"max_hp"`
	CurrentHp   int16              `json:"current_hp"`
	MajorWound  bool               `json:"major_wound"`
	Unconscious bool               `json:"unconscious"`
	Dying       bool               `json:"dying"`
	Dead        bool               `json:"dead"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LuckState struct {
	ID           pgtype.UUID        `json:"id"`
	CharacterID  pgtype.UUID        `json:"character_id"`
	StartingLuck int16              `json:"starting_luck"`
	CurrentLuck  int16              `json:"current_luck"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MagicState struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	MaxMp       int16              `json:"max_mp"`
	CurrentMp   int16              `json:"current_mp"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerID        string             `json:"owner_id"`
	MaxPlayers     int32              `json:"max_players"`
	InviteToken    string             `json:"invite_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PasswordHash   string             `json:"password_hash"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
}

type RoomEvent struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	ActorID   string             `json:"actor_id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	ID          pgtype.UUID        `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	UserID      string             `json:"user_id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type SanityState struct {
	ID            pgtype.UUID        `json:"id"`
	CharacterID   pgtype.UUID        `json:"character_id"`
	MaxSanity     int16              `json:"max_sanity"`
	CurrentSanity int16              `json:"current_sanity"`
	TempInsanity  bool               `json:"temp_insanity"`
	IndefInsanity bool               `json:"indef_insanity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Skill struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	Name        string             `json:"name"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	BaseValue   int16              `json:"base_value"`
	Value       int16              `json:"value"`
	Checked     bool               `json:"checked"`
	Specialized bool               `json:"specialized"`
	SpecialtyID pgtype.UUID        `json:"specialty_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SkillsCategory struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SkillsSpecialty struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	BaseValue   int16              `json:"base_value"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        string             `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	AvatarUrl *string            `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
