// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patchCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const patchCharacter = `-- name: PatchCharacter :one
UPDATE characters
SET
    name = CASE WHEN $1::boolean THEN $2::text ELSE name END,
    player_name = CASE WHEN $3::boolean THEN $4::text ELSE player_name END,
    occupation = CASE WHEN $5::boolean THEN $6::text ELSE occupation END,
    age = CASE WHEN $7::boolean THEN $8::smallint ELSE age END,
    sex = CASE WHEN $9::boolean THEN $10::text ELSE sex END,
    residence = CASE WHEN $11::boolean THEN $12::text ELSE residence END,
    birthplace = CASE WHEN $13::boolean THEN $14::text ELSE birthplace END,
    updated_at = NOW()
WHERE user_id = $15
  AND id = $16
RETURNING id, user_id, name, player_name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_key
`

type PatchCharacterParams struct {
	SetName       bool        `json:"set_name"`
	Name          string      `json:"name"`
	SetPlayerName bool        `json:"set_player_name"`
	PlayerName    *string     `json:"player_name"`
	SetOccupation bool        `json:"set_occupation"`
	Occupation    *string     `json:"occupation"`
	SetAge        bool        `json:"set_age"`
	Age           *int16      `json:"age"`
	SetSex        bool        `json:"set_sex"`
	Sex           *string     `json:"sex"`
	SetResidence  bool        `json:"set_residence"`
	Residence     *string     `json:"residence"`
	SetBirthplace bool        `json:"set_birthplace"`
	Birthplace    *string     `json:"birthplace"`
	UserID        string      `json:"user_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) PatchCharacter(ctx context.Context, arg PatchCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, patchCharacter,
		arg.SetName,
		arg.Name,
		arg.SetPlayerName,
		arg.PlayerName,
		arg.SetOccupation,
		arg.Occupation,
		arg.SetAge,
		arg.Age,
		arg.SetSex,
		arg.Sex,
		arg.SetResidence,
		arg.Residence,
		arg.SetBirthplace,
		arg.Birthplace,
		arg.UserID,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PlayerName,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitKey,
	)
	return i, err
}
