// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: removeMember.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const removeMember = `-- name: RemoveMember :one
DELETE FROM room_members WHERE room_id = $1 AND user_id = $2
RETURNING id, room_id, user_id, character_id, role, joined_at
`

type RemoveMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, removeMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
