// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replacePortrait.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockCharacterForPortraitReplacement = `-- name: LockCharacterForPortraitReplacement :one
SELECT id, user_id, name, player_name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_key
FROM characters
WHERE user_id = $1
  AND id = $2
FOR UPDATE
`

type LockCharacterForPortraitReplacementParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) LockCharacterForPortraitReplacement(ctx context.Context, arg LockCharacterForPortraitReplacementParams) (Character, error) {
	row := q.db.QueryRow(ctx, lockCharacterForPortraitReplacement, arg.UserID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PlayerName,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitKey,
	)
	return i, err
}

const setCharacterPortraitKey = `-- name: SetCharacterPortraitKey :one
UPDATE characters
SET
    portrait_key = $3,
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
RETURNING id, user_id, name, player_name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_key
`

type SetCharacterPortraitKeyParams struct {
	UserID      string      `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
	PortraitKey *string     `json:"portrait_key"`
}

func (q *Queries) SetCharacterPortraitKey(ctx context.Context, arg SetCharacterPortraitKeyParams) (Character, error) {
	row := q.db.QueryRow(ctx, setCharacterPortraitKey, arg.UserID, arg.ID, arg.PortraitKey)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PlayerName,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitKey,
	)
	return i, err
}
