// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: syncDynamicSkillBases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const syncDynamicSkillBases = `-- name: SyncDynamicSkillBases :exec
UPDATE skills s
SET
    base_value = CASE s.base_rule
        WHEN 'dodge' THEN (COALESCE($1::smallint, 0) / 2)::smallint
        WHEN 'native_language' THEN COALESCE($2::smallint, 0)
        ELSE s.base_value
    END,
    updated_at = NOW()
FROM characters c
WHERE c.id = s.character_id
  AND c.user_id = $3
  AND s.character_id = $4
  AND s.base_rule IS NOT NULL
`

type SyncDynamicSkillBasesParams struct {
	Dexterity   *int16      `json:"dexterity"`
	Education   *int16      `json:"education"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) SyncDynamicSkillBases(ctx context.Context, arg SyncDynamicSkillBasesParams) error {
	_, err := q.db.Exec(ctx, syncDynamicSkillBases,
		arg.Dexterity,
		arg.Education,
		arg.UserID,
		arg.CharacterID,
	)
	return err
}
