// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: touchRoomActivity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const touchRoomActivity = `-- name: TouchRoomActivity :one
UPDATE rooms
SET
    last_activity_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, max_players, invite_token, created_at, updated_at, password_hash, last_activity_at, name, event_sequence
`

func (q *Queries) TouchRoomActivity(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, touchRoomActivity, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.LastActivityAt,
		&i.Name,
		&i.EventSequence,
	)
	return i, err
}
