// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transferOwnership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const transferRoomOwnership = `-- name: TransferRoomOwnership :one
UPDATE rooms
SET owner_id = $1, updated_at = NOW()
WHERE rooms.id = $2
  AND owner_id = $3
  AND EXISTS (
    SELECT 1
    FROM room_members
    WHERE room_id = $2 AND user_id = $1
  )
RETURNING rooms.id, rooms.owner_id, rooms.max_players, rooms.invite_token, rooms.created_at, rooms.updated_at, rooms.password_hash
`

type TransferRoomOwnershipParams struct {
	NewOwnerID string      `json:"new_owner_id"`
	ID         pgtype.UUID `json:"id"`
	OwnerID    string      `json:"owner_id"`
}

func (q *Queries) TransferRoomOwnership(ctx context.Context, arg TransferRoomOwnershipParams) (Room, error) {
	row := q.db.QueryRow(ctx, transferRoomOwnership, arg.NewOwnerID, arg.ID, arg.OwnerID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}
