// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET
    name = $3,
    occupation = $4,
    age = $5,
    sex = $6,
    residence = $7,
    birthplace = $8,
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
RETURNING id, user_id, name, occupation, age, sex, residence, birthplace, created_at, updated_at, portrait_key
`

type UpdateCharacterParams struct {
	UserID     string      `json:"user_id"`
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Occupation *string     `json:"occupation"`
	Age        *int16      `json:"age"`
	Sex        *string     `json:"sex"`
	Residence  *string     `json:"residence"`
	Birthplace *string     `json:"birthplace"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Occupation,
		arg.Age,
		arg.Sex,
		arg.Residence,
		arg.Birthplace,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Occupation,
		&i.Age,
		&i.Sex,
		&i.Residence,
		&i.Birthplace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortraitKey,
	)
	return i, err
}
