// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateNote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateNote = `-- name: UpdateNote :one
UPDATE notes n
SET
    title = $1,
    body = $2,
    updated_at = NOW()
FROM characters c
WHERE c.id = n.character_id
  AND c.user_id = $3
  AND n.character_id = $4
  AND n.id = $5
RETURNING n.id, n.character_id, n.title, n.body, n.created_at, n.updated_at
`

type UpdateNoteParams struct {
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	NoteID      pgtype.UUID `json:"note_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.UserID,
		arg.CharacterID,
		arg.NoteID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
