// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateRoom.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET max_players = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, max_players, created_at, updated_at
`

type UpdateRoomParams struct {
	ID         pgtype.UUID `json:"id"`
	MaxPlayers int32       `json:"max_players"`
	OwnerID    string      `json:"owner_id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.ID, arg.MaxPlayers, arg.OwnerID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
