// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateMemberCharacter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateMemberCharacter = `-- name: UpdateMemberCharacter :one
UPDATE room_members rm
SET character_id = $3
WHERE rm.room_id = $1 AND rm.user_id = $2
  AND EXISTS (SELECT 1 FROM characters c WHERE c.id = $3 AND c.user_id = $2)
RETURNING id, room_id, user_id, character_id, role, joined_at
`

type UpdateMemberCharacterParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) UpdateMemberCharacter(ctx context.Context, arg UpdateMemberCharacterParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, updateMemberCharacter, arg.RoomID, arg.UserID, arg.CharacterID)
	var i RoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
