// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCharacterSkill = `-- name: UpdateCharacterSkill :one
WITH updated AS (
    UPDATE skills s
    SET
        name = $1,
        category_id = $2,
        base_value = $3,
        value = $4,
        checked = $5,
        updated_at = NOW()
    FROM characters c
    WHERE c.id = s.character_id
      AND c.user_id = $6
      AND s.character_id = $7
      AND s.id = $8
    RETURNING s.id, s.character_id, s.name, s.category_id, s.base_value, s.value, s.checked, s.created_at, s.updated_at, s.is_protected, s.base_rule
)
SELECT updated.id, updated.character_id, updated.name, updated.category_id, updated.base_value, updated.value, updated.checked, updated.created_at, updated.updated_at, updated.is_protected, updated.base_rule,
    sc.name as category_name
FROM updated
JOIN skills_categories sc ON updated.category_id = sc.id
`

type UpdateCharacterSkillParams struct {
	Name        string      `json:"name"`
	CategoryID  pgtype.UUID `json:"category_id"`
	BaseValue   int16       `json:"base_value"`
	Value       int16       `json:"value"`
	Checked     bool        `json:"checked"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	SkillID     pgtype.UUID `json:"skill_id"`
}

type UpdateCharacterSkillRow struct {
	ID           pgtype.UUID        `json:"id"`
	CharacterID  pgtype.UUID        `json:"character_id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	BaseValue    int16              `json:"base_value"`
	Value        int16              `json:"value"`
	Checked      bool               `json:"checked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsProtected  bool               `json:"is_protected"`
	BaseRule     *string            `json:"base_rule"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) UpdateCharacterSkill(ctx context.Context, arg UpdateCharacterSkillParams) (UpdateCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, updateCharacterSkill,
		arg.Name,
		arg.CategoryID,
		arg.BaseValue,
		arg.Value,
		arg.Checked,
		arg.UserID,
		arg.CharacterID,
		arg.SkillID,
	)
	var i UpdateCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.CategoryID,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
		&i.BaseRule,
		&i.CategoryName,
	)
	return i, err
}
