// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateRoom.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET
    max_players = $1,
    password_hash = COALESCE($2, password_hash),
    updated_at = NOW()
WHERE id = $3 AND owner_id = $4
RETURNING id, owner_id, max_players, invite_token, created_at, updated_at, password_hash, last_activity_at
`

type UpdateRoomParams struct {
	MaxPlayers   int32       `json:"max_players"`
	PasswordHash *string     `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
	OwnerID      string      `json:"owner_id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.MaxPlayers,
		arg.PasswordHash,
		arg.ID,
		arg.OwnerID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MaxPlayers,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.LastActivityAt,
	)
	return i, err
}
