// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateBackstoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateBackstoryItem = `-- name: UpdateBackstoryItem :one
UPDATE backstory_items bi
SET
    section = $1,
    title = $2,
    text = $3,
    updated_at = NOW()
FROM backstories b
JOIN characters c ON c.id = b.character_id
WHERE b.id = bi.backstory_id
  AND c.user_id = $4
  AND b.character_id = $5
  AND bi.id = $6
RETURNING bi.id, bi.backstory_id, bi.section, bi.title, bi.text, bi.created_at, bi.updated_at
`

type UpdateBackstoryItemParams struct {
	Section         string      `json:"section"`
	Title           string      `json:"title"`
	Text            string      `json:"text"`
	UserID          string      `json:"user_id"`
	CharacterID     pgtype.UUID `json:"character_id"`
	BackstoryItemID pgtype.UUID `json:"backstory_item_id"`
}

func (q *Queries) UpdateBackstoryItem(ctx context.Context, arg UpdateBackstoryItemParams) (BackstoryItem, error) {
	row := q.db.QueryRow(ctx, updateBackstoryItem,
		arg.Section,
		arg.Title,
		arg.Text,
		arg.UserID,
		arg.CharacterID,
		arg.BackstoryItemID,
	)
	var i BackstoryItem
	err := row.Scan(
		&i.ID,
		&i.BackstoryID,
		&i.Section,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
