// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateNote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
    title = $3,
    body = $4,
    updated_at = NOW()
WHERE character_id = $1 AND id = $2
RETURNING id, character_id, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.CharacterID,
		arg.ID,
		arg.Title,
		arg.Body,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
