// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateInventoryItem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE character_inventory_items inventory_item
SET
    name = $1,
    quantity = $2,
    category = $3,
    description = $4,
    updated_at = NOW()
FROM characters character
WHERE character.id = inventory_item.character_id
  AND character.user_id = $5
  AND inventory_item.character_id = $6
  AND inventory_item.id = $7
RETURNING inventory_item.id, inventory_item.character_id, inventory_item.name, inventory_item.quantity, inventory_item.category, inventory_item.description, inventory_item.created_at, inventory_item.updated_at
`

type UpdateInventoryItemParams struct {
	Name        string      `json:"name"`
	Quantity    *int32      `json:"quantity"`
	Category    *string     `json:"category"`
	Description *string     `json:"description"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	ItemID      pgtype.UUID `json:"item_id"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (CharacterInventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.Name,
		arg.Quantity,
		arg.Category,
		arg.Description,
		arg.UserID,
		arg.CharacterID,
		arg.ItemID,
	)
	var i CharacterInventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Quantity,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
