// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateMemberRole.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE room_members
SET role = $3
WHERE room_id = $1 AND user_id = $2
RETURNING id, room_id, user_id, character_id, role, joined_at
`

type UpdateMemberRoleParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID string      `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.RoomID, arg.UserID, arg.Role)
	var i RoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
