// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateCharacterSkill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCharacterSkill = `-- name: UpdateCharacterSkill :one
WITH updated AS (
    UPDATE skills s
    SET
        name = $1,
        base_value = $2,
        value = $3,
        checked = $4,
        updated_at = NOW()
    FROM characters c
    WHERE c.id = s.character_id
      AND c.user_id = $5
      AND s.character_id = $6
      AND s.id = $7
    RETURNING s.id, s.character_id, s.name, s.base_value, s.value, s.checked, s.created_at, s.updated_at, s.is_protected, s.base_rule
)
SELECT id, character_id, name, base_value, value, checked, created_at, updated_at, is_protected, base_rule FROM updated
`

type UpdateCharacterSkillParams struct {
	Name        string      `json:"name"`
	BaseValue   int16       `json:"base_value"`
	Value       int16       `json:"value"`
	Checked     bool        `json:"checked"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	SkillID     pgtype.UUID `json:"skill_id"`
}

type UpdateCharacterSkillRow struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	Name        string             `json:"name"`
	BaseValue   int16              `json:"base_value"`
	Value       int16              `json:"value"`
	Checked     bool               `json:"checked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsProtected bool               `json:"is_protected"`
	BaseRule    *string            `json:"base_rule"`
}

func (q *Queries) UpdateCharacterSkill(ctx context.Context, arg UpdateCharacterSkillParams) (UpdateCharacterSkillRow, error) {
	row := q.db.QueryRow(ctx, updateCharacterSkill,
		arg.Name,
		arg.BaseValue,
		arg.Value,
		arg.Checked,
		arg.UserID,
		arg.CharacterID,
		arg.SkillID,
	)
	var i UpdateCharacterSkillRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.BaseValue,
		&i.Value,
		&i.Checked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
		&i.BaseRule,
	)
	return i, err
}
