// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertSanityState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSanityState = `-- name: UpsertSanityState :one
WITH input AS (
    SELECT
        $3::smallint AS max_sanity,
        $4::smallint AS current_sanity,
        $5::boolean AS temp_insanity,
        $6::boolean AS indef_insanity
)

INSERT INTO sanity_states (
    character_id,
    max_sanity,
    current_sanity,
    temp_insanity,
    indef_insanity
)
SELECT
    c.id,
    COALESCE(input.max_sanity, s.max_sanity, 1),
    COALESCE(input.current_sanity, s.current_sanity, 1),
    COALESCE(input.temp_insanity, s.temp_insanity, FALSE),
    COALESCE(input.indef_insanity, s.indef_insanity, FALSE)
FROM characters c
CROSS JOIN input
LEFT JOIN sanity_states s ON s.character_id = c.id
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    max_sanity = EXCLUDED.max_sanity,
    current_sanity = EXCLUDED.current_sanity,
    temp_insanity = EXCLUDED.temp_insanity,
    indef_insanity = EXCLUDED.indef_insanity,
    updated_at = NOW()
RETURNING id, character_id, max_sanity, current_sanity, temp_insanity, indef_insanity, created_at, updated_at
`

type UpsertSanityStateParams struct {
	UserID        string      `json:"user_id"`
	CharacterID   pgtype.UUID `json:"character_id"`
	MaxSanity     *int16      `json:"max_sanity"`
	CurrentSanity *int16      `json:"current_sanity"`
	TempInsanity  *bool       `json:"temp_insanity"`
	IndefInsanity *bool       `json:"indef_insanity"`
}

func (q *Queries) UpsertSanityState(ctx context.Context, arg UpsertSanityStateParams) (SanityState, error) {
	row := q.db.QueryRow(ctx, upsertSanityState,
		arg.UserID,
		arg.CharacterID,
		arg.MaxSanity,
		arg.CurrentSanity,
		arg.TempInsanity,
		arg.IndefInsanity,
	)
	var i SanityState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxSanity,
		&i.CurrentSanity,
		&i.TempInsanity,
		&i.IndefInsanity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
