// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertBackstory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertBackstory = `-- name: UpsertBackstory :one
WITH input AS (
    SELECT $3::text AS personal_description
)
INSERT INTO backstories (
    character_id,
    personal_description
)
SELECT
    c.id,
    input.personal_description
FROM characters c
CROSS JOIN input
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    personal_description = COALESCE((SELECT personal_description FROM input), backstories.personal_description),
    updated_at = NOW()
RETURNING id, character_id, personal_description, created_at, updated_at
`

type UpsertBackstoryParams struct {
	UserID              string      `json:"user_id"`
	CharacterID         pgtype.UUID `json:"character_id"`
	PersonalDescription *string     `json:"personal_description"`
}

func (q *Queries) UpsertBackstory(ctx context.Context, arg UpsertBackstoryParams) (Backstory, error) {
	row := q.db.QueryRow(ctx, upsertBackstory, arg.UserID, arg.CharacterID, arg.PersonalDescription)
	var i Backstory
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.PersonalDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
