// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertCharacteristics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertCharacteristics = `-- name: UpsertCharacteristics :one
INSERT INTO characteristics (
    character_id,
    strength,
    constitution,
    size,
    dexterity,
    appearance,
    intelligence,
    power,
    education
)
SELECT
    c.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
FROM characters c
WHERE c.user_id = $9
  AND c.id = $10
ON CONFLICT (character_id) DO UPDATE
SET
    strength = EXCLUDED.strength,
    constitution = EXCLUDED.constitution,
    size = EXCLUDED.size,
    dexterity = EXCLUDED.dexterity,
    appearance = EXCLUDED.appearance,
    intelligence = EXCLUDED.intelligence,
    power = EXCLUDED.power,
    education = EXCLUDED.education,
    updated_at = NOW()
RETURNING id, character_id, strength, constitution, size, dexterity, appearance, intelligence, power, education, created_at, updated_at
`

type UpsertCharacteristicsParams struct {
	Strength     *int16      `json:"strength"`
	Constitution *int16      `json:"constitution"`
	Size         *int16      `json:"size"`
	Dexterity    *int16      `json:"dexterity"`
	Appearance   *int16      `json:"appearance"`
	Intelligence *int16      `json:"intelligence"`
	Power        *int16      `json:"power"`
	Education    *int16      `json:"education"`
	UserID       string      `json:"user_id"`
	CharacterID  pgtype.UUID `json:"character_id"`
}

func (q *Queries) UpsertCharacteristics(ctx context.Context, arg UpsertCharacteristicsParams) (Characteristic, error) {
	row := q.db.QueryRow(ctx, upsertCharacteristics,
		arg.Strength,
		arg.Constitution,
		arg.Size,
		arg.Dexterity,
		arg.Appearance,
		arg.Intelligence,
		arg.Power,
		arg.Education,
		arg.UserID,
		arg.CharacterID,
	)
	var i Characteristic
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Strength,
		&i.Constitution,
		&i.Size,
		&i.Dexterity,
		&i.Appearance,
		&i.Intelligence,
		&i.Power,
		&i.Education,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
