// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertHealthState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertHealthState = `-- name: UpsertHealthState :one
INSERT INTO health_states (
    character_id,
    max_hp,
    current_hp,
    major_wound,
    unconscious,
    dying,
    dead
)
SELECT
    c.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM characters c
WHERE c.user_id = $7
  AND c.id = $8
ON CONFLICT (character_id) DO UPDATE
SET
    max_hp = EXCLUDED.max_hp,
    current_hp = EXCLUDED.current_hp,
    major_wound = EXCLUDED.major_wound,
    unconscious = EXCLUDED.unconscious,
    dying = EXCLUDED.dying,
    dead = EXCLUDED.dead,
    updated_at = NOW()
RETURNING id, character_id, max_hp, current_hp, major_wound, unconscious, dying, dead, created_at, updated_at
`

type UpsertHealthStateParams struct {
	MaxHp       int16       `json:"max_hp"`
	CurrentHp   int16       `json:"current_hp"`
	MajorWound  bool        `json:"major_wound"`
	Unconscious bool        `json:"unconscious"`
	Dying       bool        `json:"dying"`
	Dead        bool        `json:"dead"`
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) UpsertHealthState(ctx context.Context, arg UpsertHealthStateParams) (HealthState, error) {
	row := q.db.QueryRow(ctx, upsertHealthState,
		arg.MaxHp,
		arg.CurrentHp,
		arg.MajorWound,
		arg.Unconscious,
		arg.Dying,
		arg.Dead,
		arg.UserID,
		arg.CharacterID,
	)
	var i HealthState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MajorWound,
		&i.Unconscious,
		&i.Dying,
		&i.Dead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
