// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertUser.sql

package db

import (
	"context"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    clerk_user_id,
    username,
    email,
    avatar_url
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (clerk_user_id)
DO UPDATE SET
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, clerk_user_id, username, email, avatar_url, created_at, updated_at
`

type UpsertUserParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ClerkUserID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
