// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertFinances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertFinances = `-- name: UpsertFinances :one
WITH input AS (
    SELECT
        $3::varchar(120) AS spending_limit,
        $4::varchar(120) AS cash,
        $5::text AS assets
)

INSERT INTO finances (
    character_id,
    spending_limit,
    cash,
    assets
)
SELECT
    c.id,
    input.spending_limit,
    input.cash,
    input.assets
FROM characters c
CROSS JOIN input
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    spending_limit = COALESCE((SELECT spending_limit FROM input), finances.spending_limit),
    cash = COALESCE((SELECT cash FROM input), finances.cash),
    assets = COALESCE((SELECT assets FROM input), finances.assets),
    updated_at = NOW()
RETURNING id, character_id, spending_limit, cash, assets, created_at, updated_at
`

type UpsertFinancesParams struct {
	UserID        string      `json:"user_id"`
	CharacterID   pgtype.UUID `json:"character_id"`
	SpendingLimit *string     `json:"spending_limit"`
	Cash          *string     `json:"cash"`
	Assets        *string     `json:"assets"`
}

func (q *Queries) UpsertFinances(ctx context.Context, arg UpsertFinancesParams) (Finance, error) {
	row := q.db.QueryRow(ctx, upsertFinances,
		arg.UserID,
		arg.CharacterID,
		arg.SpendingLimit,
		arg.Cash,
		arg.Assets,
	)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.SpendingLimit,
		&i.Cash,
		&i.Assets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
