// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertMagicState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertMagicState = `-- name: UpsertMagicState :one
WITH input AS (
    SELECT
        $3::smallint AS max_mp,
        $4::smallint AS current_mp
)

INSERT INTO magic_states (
    character_id,
    max_mp,
    current_mp
)
SELECT
    c.id,
    COALESCE(input.max_mp, m.max_mp, 1),
    COALESCE(input.current_mp, m.current_mp, 1)
FROM characters c
CROSS JOIN input
LEFT JOIN magic_states m ON m.character_id = c.id
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    max_mp = EXCLUDED.max_mp,
    current_mp = EXCLUDED.current_mp,
    updated_at = NOW()
RETURNING id, character_id, max_mp, current_mp, created_at, updated_at
`

type UpsertMagicStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	MaxMp       *int16      `json:"max_mp"`
	CurrentMp   *int16      `json:"current_mp"`
}

func (q *Queries) UpsertMagicState(ctx context.Context, arg UpsertMagicStateParams) (MagicState, error) {
	row := q.db.QueryRow(ctx, upsertMagicState,
		arg.UserID,
		arg.CharacterID,
		arg.MaxMp,
		arg.CurrentMp,
	)
	var i MagicState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxMp,
		&i.CurrentMp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
