// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertDerivedStats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertDerivedStats = `-- name: UpsertDerivedStats :one
WITH input AS (
    SELECT
        $3::smallint AS speed,
        $4::smallint AS physique,
        $5::varchar(16) AS damage_bonus,
        $6::smallint AS dodge_value
)

INSERT INTO derived_stats (
    character_id,
    speed,
    physique,
    damage_bonus,
    dodge_value
)
SELECT
    c.id,
    input.speed,
    input.physique,
    input.damage_bonus,
    input.dodge_value
FROM characters c
CROSS JOIN input
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    speed = COALESCE((SELECT speed FROM input), derived_stats.speed),
    physique = COALESCE((SELECT physique FROM input), derived_stats.physique),
    damage_bonus = COALESCE((SELECT damage_bonus FROM input), derived_stats.damage_bonus),
    dodge_value = COALESCE((SELECT dodge_value FROM input), derived_stats.dodge_value),
    updated_at = NOW()
RETURNING id, character_id, speed, physique, damage_bonus, dodge_value, created_at, updated_at
`

type UpsertDerivedStatsParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	Speed       *int16      `json:"speed"`
	Physique    *int16      `json:"physique"`
	DamageBonus *string     `json:"damage_bonus"`
	DodgeValue  *int16      `json:"dodge_value"`
}

func (q *Queries) UpsertDerivedStats(ctx context.Context, arg UpsertDerivedStatsParams) (DerivedStat, error) {
	row := q.db.QueryRow(ctx, upsertDerivedStats,
		arg.UserID,
		arg.CharacterID,
		arg.Speed,
		arg.Physique,
		arg.DamageBonus,
		arg.DodgeValue,
	)
	var i DerivedStat
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Speed,
		&i.Physique,
		&i.DamageBonus,
		&i.DodgeValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
