// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertLuckState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertLuckState = `-- name: UpsertLuckState :one
WITH input AS (
    SELECT
        $3::smallint AS starting_luck,
        $4::smallint AS current_luck
)

INSERT INTO luck_states (
    character_id,
    starting_luck,
    current_luck
)
SELECT
    c.id,
    COALESCE(input.starting_luck, 1),
    COALESCE(input.current_luck, 1)
FROM characters c
CROSS JOIN input
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    starting_luck = COALESCE((SELECT starting_luck FROM input), luck_states.starting_luck),
    current_luck = COALESCE((SELECT current_luck FROM input), luck_states.current_luck),
    updated_at = NOW()
RETURNING id, character_id, starting_luck, current_luck, created_at, updated_at
`

type UpsertLuckStateParams struct {
	UserID       string      `json:"user_id"`
	CharacterID  pgtype.UUID `json:"character_id"`
	StartingLuck *int16      `json:"starting_luck"`
	CurrentLuck  *int16      `json:"current_luck"`
}

func (q *Queries) UpsertLuckState(ctx context.Context, arg UpsertLuckStateParams) (LuckState, error) {
	row := q.db.QueryRow(ctx, upsertLuckState,
		arg.UserID,
		arg.CharacterID,
		arg.StartingLuck,
		arg.CurrentLuck,
	)
	var i LuckState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.StartingLuck,
		&i.CurrentLuck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
