// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsertHealthState.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertHealthState = `-- name: UpsertHealthState :one
WITH input AS (
    SELECT
        $3::smallint AS max_hp,
        $4::smallint AS current_hp,
        $5::boolean AS major_wound,
        $6::boolean AS unconscious,
        $7::boolean AS dying,
        $8::boolean AS dead
)

INSERT INTO health_states (
    character_id,
    max_hp,
    current_hp,
    major_wound,
    unconscious,
    dying,
    dead
)
SELECT
    c.id,
    COALESCE(input.max_hp, h.max_hp, 1),
    COALESCE(input.current_hp, h.current_hp, 1),
    COALESCE(input.major_wound, h.major_wound, FALSE),
    COALESCE(input.unconscious, h.unconscious, FALSE),
    COALESCE(input.dying, h.dying, FALSE),
    COALESCE(input.dead, h.dead, FALSE)
FROM characters c
CROSS JOIN input
LEFT JOIN health_states h ON h.character_id = c.id
WHERE c.user_id = $1
  AND c.id = $2
ON CONFLICT (character_id) DO UPDATE
SET
    max_hp = EXCLUDED.max_hp,
    current_hp = EXCLUDED.current_hp,
    major_wound = EXCLUDED.major_wound,
    unconscious = EXCLUDED.unconscious,
    dying = EXCLUDED.dying,
    dead = EXCLUDED.dead,
    updated_at = NOW()
RETURNING id, character_id, max_hp, current_hp, major_wound, unconscious, dying, dead, created_at, updated_at
`

type UpsertHealthStateParams struct {
	UserID      string      `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	MaxHp       *int16      `json:"max_hp"`
	CurrentHp   *int16      `json:"current_hp"`
	MajorWound  *bool       `json:"major_wound"`
	Unconscious *bool       `json:"unconscious"`
	Dying       *bool       `json:"dying"`
	Dead        *bool       `json:"dead"`
}

func (q *Queries) UpsertHealthState(ctx context.Context, arg UpsertHealthStateParams) (HealthState, error) {
	row := q.db.QueryRow(ctx, upsertHealthState,
		arg.UserID,
		arg.CharacterID,
		arg.MaxHp,
		arg.CurrentHp,
		arg.MajorWound,
		arg.Unconscious,
		arg.Dying,
		arg.Dead,
	)
	var i HealthState
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MajorWound,
		&i.Unconscious,
		&i.Dying,
		&i.Dead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
